version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.0.1

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
    docker:
      - image: cimg/ruby:3.0.4-node
        environment:
          RAILS_ENV: test
          PGHOST: 127.0.0.1
          DATABASE_URL: "postgres://postgres@localhost:5432/imdbclone_test"
      - image: circleci/postgres:12.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: imdbclone_test
          POSTGRES_HOST_AUTH_METHOD: trust
caches:
  - &bundle_cache_full v2-repo-{{ checksum "Gemfile.lock" }}

commands:
  defaults:
    steps:
      - checkout
      - restore_cache:
          keys:
            - *bundle_cache_full
      - run: bundle check || bundle install

      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load

      - save_cache:
          key: *bundle_cache_full
          paths:
            - vendor/bundle

  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop -P
      - run:
          name: fasterer
          command: bundle exec fasterer
  run_specs:
    steps:
      - run:
          name: run specs
          command: bundle exec rspec

jobs:
  lintering:
    executor: default
    steps:
      - defaults
      - run_linters
  run_specs:
    executor: default
    steps:
      - defaults
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run_specs

workflows:
  version: 2
  build:
    jobs:
      - lintering
      - run_specs:
          requires:
            - lintering

